### POST request to sign a valid event
POST {{host}}/sign
Content-Type: application/json

{
  "pubkey": "79be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798",
  "created_at": 1710777600,
  "kind": 1,
  "tags": [],
  "content": "Hello, Nostr from Bancwr Diogel!"
}

> ../../asserts/should_be_200_ok.js

### POST request to sign with empty content (should fail)
POST {{host}}/sign
Content-Type: application/json

{
  "pubkey": "79be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798",
  "created_at": 1710777600,
  "kind": 1,
  "tags": [],
  "content": ""
}

> ../../asserts/should_be_400_bad_request.js

### POST request to sign with forbidden kind 0 (should fail)
POST {{host}}/sign
Content-Type: application/json

{
  "pubkey": "79be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798",
  "created_at": 1710777600,
  "kind": 0,
  "tags": [],
  "content": "This should be blocked"
}

> ../../asserts/should_be_400_bad_request.js
